use_frameworks!

platform :ios, '8.0'

target 'MJPlaceholderView_Example' do
  pod 'MJPlaceholderView', :path => '../'

  target 'MJPlaceholderView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
