use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'MJPlaceholderView_Example' do
  pod 'MJPlaceholderView', :path => '../'
  pod 'MJRefresh'
  target 'MJPlaceholderView_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
